# Setup
title:               Chillog
tagline:             '차가운 블로그'
description:         '배움에는 뜨겁고 감성적이게, 개발은 차갑고 이성적으로'
url:                 https://chillyMind.github.io
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Jeoungwook Lee
  url:               https://chillyMind.github.io
  email:             do@visioninmind.net

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
